### 1. Create a random tensor with shape (7, 7)

In [6]:
import torch
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [1]:
x = torch.rand(size=(7, 7))
x

tensor([[9.3479e-01, 6.7800e-01, 2.3120e-01, 1.9342e-01, 5.3096e-01, 5.4638e-01,
         5.2512e-01],
        [9.4686e-01, 6.0252e-01, 7.9556e-01, 6.1765e-01, 8.8428e-01, 6.2534e-01,
         1.9815e-01],
        [7.6417e-01, 7.1609e-01, 9.1243e-04, 9.8395e-01, 5.4021e-01, 8.1691e-01,
         2.7449e-01],
        [4.0338e-01, 2.9568e-01, 6.7460e-01, 8.6250e-01, 2.9857e-01, 8.9737e-01,
         2.8740e-01],
        [7.0391e-01, 1.3548e-01, 3.8050e-02, 4.5830e-01, 1.2010e-01, 8.8201e-01,
         8.7333e-01],
        [2.2861e-01, 4.0395e-01, 6.9191e-01, 5.1021e-01, 6.1915e-01, 1.8140e-01,
         3.8737e-01],
        [6.1494e-03, 8.7480e-01, 5.1443e-01, 9.5532e-01, 2.7301e-01, 4.8462e-01,
         9.1453e-01]])

### 2. Perform a matrix multiplication with tensor `x` and another random tensor, `y`, with shape (1, 7)

In [7]:
y = torch.rand(size=(1, 7))
y

tensor([[0.1954, 0.6752, 0.1897, 0.5014, 0.4376, 0.3033, 0.4275]])

In [8]:
z = torch.matmul(x, y.T)
z

tensor([[1.4038],
        [1.7138],
        [1.7279],
        [1.3646],
        [1.1594],
        [1.1961],
        [1.8259]])

### 3. Set a random seed and repeat exercises 1 and 2

In [10]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

x = torch.rand(size=(7, 7))
y = torch.rand(size=(1, 7))
z = torch.matmul(x, y.T)
z

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 4. Set the random seed, but for the GPU you're currently using

In [13]:
RANDOM_SEED_GPU = 1234
torch.mps.manual_seed(RANDOM_SEED_GPU)

### 5. Create two random tensors of shape (2, 3) and send the mboth to the GPU. Set `torch.manual_seed(1234)` when creating the tensors.

In [14]:
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

x = torch.rand(size=(2, 3)).to(device)
y = torch.rand(size=(2, 3)).to(device)
x, x.device, y, y.device

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 device(type='mps', index=0),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'),
 device(type='mps', index=0))

### 6. Perform a matrix multiplication of tensors from 5.

In [16]:
z = torch.matmul(x, y.T)
z

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='mps:0')

### 7. Find the max and min values for ouput of 6

In [17]:
z.min(), z.max()

(tensor(0.3647, device='mps:0'), tensor(0.5617, device='mps:0'))

### 8. Find min and max indexes for ouput of 6

In [18]:
z.argmin(), z.argmax()

(tensor(0, device='mps:0'), tensor(3, device='mps:0'))

### 9. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the dimensions `1` removed to be left with tensor of shape `(10)`. Set the seed to `7` when you create and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [19]:
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

x = torch.rand(size=(1, 1, 1, 10))
y = x.squeeze()
x, x.shape, y, y.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))