# 00. PyTorch Fundamentals

In [1]:
import torch
print (torch.__version__)

2.1.0+cu121


## Introduction to tensors
Tensors are being created using `torch.tensor()`

### Scalar

In [2]:
# Scalar - 0 dims
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Attributes
scalar.ndim

0

In [4]:
# Get item list
scalar.item()

7

### Vector

In [5]:
# Vector
vector = torch.tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

### Matrix

In [8]:
# Matrix
matrix = torch.tensor([[1, 2],
                       [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

### Tensor

In [11]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

### Random tensors

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1648, 0.3702, 0.6013, 0.2431],
        [0.2902, 0.7216, 0.9982, 0.7098],
        [0.8624, 0.7877, 0.6071, 0.7023]])

In [15]:
random_tensor.ndim

2

In [16]:
# Create a random tensor with similar shape image
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.4335, 0.7731, 0.8311],
          [0.8396, 0.0969, 0.7207],
          [0.4436, 0.4590, 0.9844],
          ...,
          [0.7449, 0.4716, 0.3928],
          [0.1231, 0.0461, 0.5532],
          [0.6918, 0.9296, 0.6681]],
 
         [[0.6683, 0.7432, 0.8730],
          [0.2227, 0.3640, 0.7765],
          [0.7700, 0.1996, 0.7171],
          ...,
          [0.7685, 0.3975, 0.1661],
          [0.8414, 0.1700, 0.0287],
          [0.4570, 0.6193, 0.2627]],
 
         [[0.6700, 0.6216, 0.7001],
          [0.4935, 0.7675, 0.1848],
          [0.7624, 0.9259, 0.5805],
          ...,
          [0.9569, 0.2150, 0.6374],
          [0.4255, 0.4702, 0.0420],
          [0.8685, 0.3437, 0.4613]],
 
         ...,
 
         [[0.4169, 0.9784, 0.6424],
          [0.5943, 0.6884, 0.9630],
          [0.4294, 0.2668, 0.4400],
          ...,
          [0.6977, 0.3818, 0.7688],
          [0.1944, 0.5507, 0.6239],
          [0.3696, 0.7986, 0.7207]],
 
         [[0.9963, 0.3802, 0.0805],
          [0

### Zeros and ones

In [17]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [20]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=10, step=1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [22]:
float_32_tensor = torch.tensor([3.0,  6.0, 9.0],
                               dtype=None,
                               device=None, # One what device the tensor is on
                               requires_grad=False) # Whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

### Getting tensor attributes
* `tensor.dtype()` - to get tensor data type
* `tensor.shape` - to get tensor shape
* `tensor.device` - to get where tensor is situated

In [24]:
rand_tensor = torch.rand(4,5)
rand_tensor

tensor([[0.6477, 0.7029, 0.3325, 0.8585, 0.2757],
        [0.6188, 0.8267, 0.0523, 0.9613, 0.3499],
        [0.1897, 0.4349, 0.2473, 0.3811, 0.5922],
        [0.1935, 0.3703, 0.7173, 0.7148, 0.6329]])

In [25]:
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Device tensor is on: {rand_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 5])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)
* addition
* substraction
* multiplication (element-wise)
* division
* matrix multiplication

In [26]:
tensor = torch.tensor([1, 2, 3])

In [27]:
torch.mul(tensor, 10), torch.add(tensor, 4)

(tensor([10, 20, 30]), tensor([5, 6, 7]))

### Matrix multiplication
Two main ways are:
* element-wise multiplication
* dot product (matrix X matrix)

In [28]:
# Element-wise
tensor * tensor

tensor([1, 4, 9])

In [29]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### Tensor transpose

In [30]:
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensorB = torch.tensor([[5,6],
                        [3,4],
                        [1,2]])
tensorA, tensorB

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[5, 6],
         [3, 4],
         [1, 2]]))

In [31]:
#torch.matmul(tensorA, tensorB)

In [32]:
tensorB.T.shape

torch.Size([2, 3])

In [33]:
torch.matmul(tensorA, tensorB.T)

tensor([[17, 11,  5],
        [39, 25, 11],
        [61, 39, 17]])

### Finding the aggregation values (min, max, mean, sum etc.)

In [34]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
x.min(), x.max()

(tensor(0), tensor(90))

In [36]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [37]:
torch.sum(x)

tensor(450)

### Finding the positional min and max

In [38]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

### Reshaping, stacking squeezing and unsqueezing
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side-by-side (hstack)
* Squeeze - removes all `1` dimension for a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [40]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
# Add an extra dimension
# x_reshaped = x.reshape(1, 7) -< invalid, we cannot fit 9 elements in 7 spots
x_reshaped = x.reshape(3, 1, 3)
x_reshaped, x_reshaped.shape

(tensor([[[1., 2., 3.]],
 
         [[4., 5., 6.]],
 
         [[7., 8., 9.]]]),
 torch.Size([3, 1, 3]))

In [45]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# Stack tensors of top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [53]:
# Squeeze
x_reshaped.squeeze(), x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 1, 3]))

In [56]:
# Unsqueeze
x_unsqueezed = x_reshaped.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[[[1., 2., 3.]]],
 
 
         [[[4., 5., 6.]]],
 
 
         [[[7., 8., 9.]]]]),
 torch.Size([3, 1, 1, 3]))

In [59]:
# Permute
x_permuted = torch.permute(x_unsqueezed, (3, 0, 1, 2))
x_permuted, x_permuted.shape

(tensor([[[[1.]],
 
          [[4.]],
 
          [[7.]]],
 
 
         [[[2.]],
 
          [[5.]],
 
          [[8.]]],
 
 
         [[[3.]],
 
          [[6.]],
 
          [[9.]]]]),
 torch.Size([3, 3, 1, 1]))

### Selecting data from tensors - indexing
Indexing in PyTorch works very similarly to indexing in Python.

In [62]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
x[0][0]

tensor([1, 2, 3])

In [67]:
x[0, 2, 2]

tensor(9)

In [68]:
# You can also use ":" to slice tensors
x[:, :, 1]

tensor([[2, 5, 8]])

In [69]:
x[:, 1, 1]

tensor([5])

In [70]:
x[0, 0, :]

tensor([1, 2, 3])

### PyTorch tensors and NumPy
* `torch.from_numpy(ndarray)`
* `torch.Tensor.numpy()`

Both transformations carry the `dtype` with them, so be aware of this as it may cause some issues in the future.

In [71]:
import torch
import numpy as np

# NumPy to PyTorch
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [72]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [74]:
tensor.type(torch.float32).dtype

torch.float32

In [75]:
# PyTorch to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [76]:
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

### PyTorch reproducibility (reducing the random in the random)

To reduce the randomness, comes the concept of a **random seed**. What it does is flavour the randomness.

In [79]:
torch.rand(3,3)

tensor([[0.7879, 0.3555, 0.8899],
        [0.8883, 0.8853, 0.3840],
        [0.9935, 0.8933, 0.8856]])

In [80]:
# Create random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [82]:
# Let's make it reproducible
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C == random_tensor_D


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and PyTorch objects on GPUs (to make faster computations)

### Basic setup

In [2]:
# Check for GPU access in Colab
!nvidia-smi

Sat Jan 13 16:18:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [6]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors and models on the GPU

In [7]:
# Create a tensor - defaults on CPU
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [8]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

### Moving tensors to CPU

In [10]:
#tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])